# Generated by Django 3.2.10 on 2022-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=2, upload_to='testimonial_thumbnail'),
            preserve_default=False,
        ),
    ]
