# Generated by Django 3.2.10 on 2022-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('software1', models.FileField(blank=True, null=True, upload_to='software')),
                ('software2', models.FileField(blank=True, null=True, upload_to='software')),
                ('software3', models.FileField(blank=True, null=True, upload_to='software')),
                ('s1_name', models.CharField(blank=True, max_length=300, null=True)),
                ('s2_name', models.CharField(blank=True, max_length=300, null=True)),
                ('s3_name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='project_image')),
            ],
        ),
    ]
